# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nGreVZ4IBlVjcltxH7WDP2n1HNcNBrCz
"""

import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
import matplotlib.pyplot as plt

file_path = "/content/Biomass_History.csv"

data  =  pd.read_csv(file_path)

data = data.dropna()

df = pd.DataFrame(data)

### generating a geojson file
geometry = [Point(xy) for xy in zip(df['Longitude'], df['Latitude'])]
gdf = gpd.GeoDataFrame(df, geometry=geometry)
gdf.to_file('main_output.geojson', driver='GeoJSON')

file_path_geojson = "/content/given_output.geojson"

gdf = gpd.read_file(file_path_geojson)

### plotting for all years

fig, ax = plt.subplots(4,2,figsize=(10, 8))
gdf.plot(column='2010', cmap='inferno', legend=True, ax=ax[0][0])
ax[0][0].set_title('Spatial Residual Plot 2010')

gdf.plot(column='2011', cmap='inferno', legend=True, ax=ax[0][1])
ax[0][1].set_title('Spatial Residual Plot 2011')

gdf.plot(column='2012', cmap='inferno', legend=True, ax=ax[1][0])
ax[1][0].set_title('Spatial Residual Plot 2012')

gdf.plot(column='2013', cmap='inferno', legend=True, ax=ax[1][1])
ax[1][1].set_title('Spatial Residual Plot 2013')

gdf.plot(column='2014', cmap='inferno', legend=True, ax=ax[2][0])
ax[2][0].set_title('Spatial Residual Plot 2014')

gdf.plot(column='2015', cmap='inferno', legend=True, ax=ax[2][1])
ax[2][1].set_title('Spatial Residual Plot 2015')

gdf.plot(column='2016', cmap='inferno', legend=True, ax=ax[3][0])
ax[3][0].set_title('Spatial Residual Plot 2016')

gdf.plot(column='2017', cmap='inferno', legend=True, ax=ax[3][1])
ax[3][1].set_title('Spatial Residual Plot 2017')

### adjusting the file
plt.tight_layout()

plt.show()

